---
- hosts: all
  become: true
  tasks:

  - name: install latest apache package and run updates
    package:
      name:
        - "{{ apache_package }}"
      state: latest
      update_cache: yes
